# Ejercicios de Numpy
Inteligencia Artificial - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [2]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [3]:
lista = [1, 2, 3, 4, 5]

vector = np.array([lista])

print(vector)

[[1 2 3 4 5]]


Ejercicio 3: Suma los siguientes dos arrays

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [5]:
resultado = np.add(a, b)
print(resultado)

[[11 13 15]
 [17 19 21]]


Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [6]:
a = np.array([[4,2,2],
              [4,1,0]])

multiplicacion = np.multiply(3.2,a)
print(multiplicacion)

[[12.8  6.4  6.4]
 [12.8  3.2  0. ]]


Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [7]:
a = np.array([x for x in range(9)])

print(np.shape(a))

a = np.reshape(a,9)
print(a)

(9,)
[0 1 2 3 4 5 6 7 8]


Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [8]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])

In [9]:
a = a.astype(int)
print(a)

[[2 3 1]
 [4 2 1]]


Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [10]:
matrix = np.eye(5,5)
print(matrix)
matrix = matrix.astype(bool)
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]


Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [11]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

In [12]:
a3 = np.concatenate((a1,a2),axis=1)

print(a3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Ejercicio 9: Cocatena de forma vertical los mismos array

In [13]:
a4 = np.concatenate((a1,a2),axis=0)

print(a4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [14]:
array_unidimensional = np.arange(0, 101, 2)

print("Array unidimensional con números del 0 al 100 con saltos de 2:")
print(array_unidimensional)


Array unidimensional con números del 0 al 100 con saltos de 2:
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [15]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

In [16]:
c = np.where(a>b)
print(c)

print(a[c])

(array([2, 4], dtype=int64),)
[3 6]


Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [17]:
secuencia = np.arange(0,101,100/5)
print(secuencia)

[  0.  20.  40.  60.  80. 100.]


Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [18]:
matrix_23 = np.full((2,3),23)
print(matrix_23)

[[23 23 23]
 [23 23 23]]


Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [19]:
random_matrix = np.random.normal(size=(8, 2))

print(random_matrix)

[[ 0.50960122 -0.36053044]
 [-1.23434503  0.78582941]
 [ 1.15870295  0.42292029]
 [-0.35917886 -1.43043003]
 [ 0.6128637   3.01411128]
 [-0.1537248  -0.51983105]
 [ 1.157415   -1.0501843 ]
 [-0.44058705  0.87642391]]


Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [20]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [26]:
a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

In [27]:
indices_ascendente = np.argsort(a)
a_ascendente = a[indices_ascendente]
print(a_ascendente)

[   0    1    2    2   38   82   91  199  292  299  387  923  939 1101]


In [28]:
indices_descendente = np.flip(indices_ascendente)
a_descendente = a[indices_descendente]

print("\nArray ordenado de forma descendente:")
print(a_descendente)


Array ordenado de forma descendente:
[1101  939  923  387  299  292  199   91   82   38    2    2    1    0]


----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [30]:
datos = np.genfromtxt('venta_libros.csv', delimiter=',', skip_header=1)

# Separa las columnas en arrays diferentes
year = datos[:, 0]
month = datos[:, 1]
books = datos[:, 2]

# Imprime los primeros elementos de cada array
print("Year:", year[:5])
print("Month:", month[:5])
print("Books:", books[:5])

Year: [2019. 2019. 2019. 2019. 2019.]
Month: [2. 3. 4. 5. 6.]
Books: [400. 339. 389. 141. 332.]


Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [36]:
max_book = books.max()
print(max_book)


489.0
(array([30], dtype=int64),)


In [40]:
indice = np.where(books == 489.0)
print(indice[0][0])
print("year libro max ventas",year[30])
print("month libro max ventas",month[30])
print("ventas book libro max ventas",books[30])

30
year libro max ventas 2021.0
month libro max ventas 8.0
ventas book libro max ventas 489.0


Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [44]:
suma = books.sum()
media = books.mean()
mediana = np.median(books)
desvio = books.std()

print("Total suma: ", suma)
print("Total media: ", media)
print("Total mediana: ", mediana)
print("Total desvio: ", desvio)

Total suma:  12436.0
Total media:  264.59574468085106
Total mediana:  276.0
Total desvio:  136.14223781788837


: 